export enum StripeProducts {
  MONTHLY_STARTER = "MONTHLY_STARTER",
  MONTHLY_PRO = "MONTHLY_PRO",
  MONTHLY_EXPERT = "MONTHLY_EXPERT",
  YEARLY_STARTER = "YEARLY_STARTER",
  YEARLY_PRO = "YEARLY_PRO",
  YEARLY_EXPERT = "YEARLY_EXPERT",
}
